# Generated by Django 2.2.3 on 2019-08-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
