# Generated by Django 2.2.3 on 2019-08-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, max_length=32)),
                ('open_from', models.DateTimeField()),
                ('open_to', models.DateTimeField()),
                ('site_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.City')),
            ],
        ),
    ]
