# Generated by Django 2.2.3 on 2019-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('tourist_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tourist_first_name', models.CharField(blank=True, max_length=32)),
                ('tourist_last_name', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('date_of_join', models.DateField(auto_now=True)),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
