# Generated by Django 2.2.3 on 2019-08-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_transportation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
