# Generated by Django 2.2.3 on 2019-08-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('guide_first_name', models.CharField(blank=True, max_length=32)),
                ('guide_last_name', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('bank_account', models.CharField(max_length=30)),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('guide_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('national_id', models.CharField(max_length=13)),
                ('licence_id', models.CharField(max_length=30)),
                ('language', models.ManyToManyField(blank=True, to='main.Language')),
            ],
        ),
    ]
