# Generated by Django 2.2.3 on 2019-08-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePhotoData',
            fields=[
                ('guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Guide')),
                ('criminal_certificate', models.ImageField(upload_to='')),
                ('national_card', models.ImageField(upload_to='')),
                ('guide_licence', models.ImageField(upload_to='')),
            ],
        ),
    ]
