# Generated by Django 2.2.3 on 2019-08-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_guidephotodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('trip_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status_is_active', models.BooleanField(default=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hours', models.IntegerField()),
                ('extra_hours', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.City')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guide')),
                ('site', models.ManyToManyField(blank=True, to='main.Site')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tourist')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transportation')),
            ],
        ),
    ]
