# Generated by Django 2.2.3 on 2019-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190811_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='open_to',
            field=models.TimeField(),
        ),
    ]
