# Generated by Django 2.2.3 on 2019-08-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190811_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
