# Generated by Django 2.2.3 on 2019-08-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190811_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_name',
            field=models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('German', 'German'), ('Italian', 'Italian'), ('Russian', 'Russian'), ('Turkish', 'Turkish'), ('Swedish', 'Swedish'), ('Greek', 'Greek'), ('French', 'French')], default='English', max_length=30),
        ),
    ]
