# Generated by Django 2.2.3 on 2019-08-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_language_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='trans_type',
            field=models.CharField(choices=[('Public Transportation', 'public'), ('Private Transportation', 'private')], default='private', max_length=30),
        ),
    ]
