# Generated by Django 2.2.3 on 2019-08-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_transportation_trans_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='date_of_join',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
